package com.bultrain.vlak_app_test

data class StationRepository(
    val id: Int,
    val name: String,
    val englishName: String
)

val stationsList: List<StationRepository> = listOf(
    StationRepository(611, "Абланица", "Ablanica"),
    StationRepository(417, "Аврамово", "Avramovo"),
    StationRepository(61, "Айтос", "Aytos"),
    StationRepository(599, "Алдомировци", "Aldomirovci"),
    StationRepository(173, "Александрово", "Aleksandrovo"),
    StationRepository(453, "Александър Димитров", "Aleksandar Dimitrov"),
    StationRepository(513, "Алфатар", "Alfatar"),
    StationRepository(538, "Анево", "Anevo"),
    StationRepository(440, "Антон", "Anton"),
    StationRepository(472, "Арковна", "Arkovna"),
    StationRepository(12, "Асеновград", "Asenovgrad"),
    StationRepository(367, "Асеново", "Asenovo"),
    StationRepository(278, "Асеновци", "Asenovci"),
    StationRepository(166, "Аспарухово", "Asparuhovo"),
    StationRepository(345, "Атолово", "Atolovo"),
    StationRepository(627, "Байково", "Baikovo"),
    StationRepository(380, "Балкан", "Balkan"),
    StationRepository(384, "Банковица", "Bankovica"),
    StationRepository(77, "Банкя", "Bankya"),
    StationRepository(255, "Банско", "Bansko"),
    StationRepository(124, "Баня", "Banya"),
    StationRepository(62, "Батановци", "Batanovci"),
    StationRepository(495, "Батишница", "Batishnica"),
    StationRepository(571, "Бачо Киро", "Bacho Kiro"),
    StationRepository(407, "Безименна", "Bezimenna"),
    StationRepository(491, "Безмер", "Bezmer"),
    StationRepository(694, "Бела Вода", "Bela Voda"),
    StationRepository(126, "Бели Извор", "Beli Izvor"),
    StationRepository(322, "Белица", "Belica"),
    StationRepository(50, "Белово", "Belovo"),
    StationRepository(58, "Белозем", "Belozem"),
    StationRepository(588, "Бело Поле", "Belo Pole"),
    StationRepository(56, "Белослав", "Beloslav"),
    StationRepository(449, "Белщица", "Belshtica"),
    StationRepository(589, "Бенковски", "Benkovski"),
    StationRepository(185, "Берковица", "Berkovica"),
    StationRepository(400, "Бисер", "Biser"),
    StationRepository(426, "Благово", "Blagovo"),
    StationRepository(51, "Благоевград", "Blagoevgrad"),
    StationRepository(396, "Благоевград - Сп.", "Blagoevgrad Stop"),
    StationRepository(324, "Благой Захариев", "Blagoi Zahariev"),
    StationRepository(298, "Бобов Дол", "Bobov Dol"),
    StationRepository(489, "Бобошево", "Boboshevo"),
    StationRepository(89, "Бов", "Bov"),
    StationRepository(330, "Богданци", "Bogdanci"),
    StationRepository(609, "Божичен", "Bozhichen"),
    StationRepository(421, "Божковци", "Bozhkovci"),
    StationRepository(398, "Божурица", "Bozhurica"),
    StationRepository(256, "Божурище", "Bozhurishte"),
    StationRepository(549, "Бозаджии", "Bozadzhii"),
    StationRepository(231, "Бойка", "Boika"),
    StationRepository(19, "Бойчиновци", "Boichinovci"),
    StationRepository(606, "Бокиловци", "Bokilovci"),
    StationRepository(102, "Борово", "Borovo"),
    StationRepository(253, "Боровци", "Borovci"),
    StationRepository(395, "Борущица", "Borushtica"),
    StationRepository(235, "Боряна", "Boryana"),
    StationRepository(444, "Ботев", "Botev"),
    StationRepository(416, "Ботево", "Botevo"),
    StationRepository(536, "Ботунец", "Botunec"),
    StationRepository(245, "Брацигово", "Bracigovo"),
    StationRepository(591, "Бригадир", "Brigadir"),
    StationRepository(640, "Бригадирска Слава", "Brigadirska Slava"),
    StationRepository(33, "Брусарци", "Brusarci"),
    StationRepository(471, "Брусен", "Brusen"),
    StationRepository(658, "Бръчма", "Brachma"),
    StationRepository(667, "Бряст", "Bryast"),
    StationRepository(377, "Буново", "Bunovo"),
    StationRepository(9, "Бургас", "Burgas"),
    StationRepository(689, "Бургас-разпределителна-спирка", "Burgas Razpredelitelna Spirka"),
    StationRepository(137, "Бургас-товарна", "Burgas Tovarna"),
    StationRepository(176, "Бутово", "Butovo"),
    StationRepository(535, "Бъзовец", "Bazovec"),
    StationRepository(461, "Българово", "Balgarovo"),
    StationRepository(553, "Бърдоква", "Bardokva"),
    StationRepository(186, "Бяга", "Byaga"),
    StationRepository(111, "Бяла", "Byala"),
    StationRepository(399, "Бял Бряг", "Byal Bryag"),
    StationRepository(115, "Вагоно-ремонтно Депо Пловдив", "Vagono-Remontno Depo Plovdiv"),
    StationRepository(53, "Вакарел", "Vakarel"),
    StationRepository(503, "Вакарел - Сп.", "Vakarel Stop"),
    StationRepository(412, "Варвара", "Varvara"),
    StationRepository(4, "Варна", "Varna"),
    StationRepository(133, "Варна - Сп.", "Varna Stop"),
    StationRepository(379, "Васил Левски", "Vasil Levski"),
    StationRepository(107, "Василовци", "Vasilovci"),
    StationRepository(443, "Ведрово", "Vedrovo"),
    StationRepository(37, "Велико Търново", "Veliko Tarnovo"),
    StationRepository(113, "Велинград", "Velingrad"),
    StationRepository(467, "Велинград Юг", "Velingrad South"),
    StationRepository(636, "Велино", "Velino"),
    StationRepository(134, "Величково", "Velichkovo"),
    StationRepository(302, "Венчан", "Venchan"),
    StationRepository(112, "Верила", "Verila"),
    StationRepository(362, "Веринско", "Verinsko"),
    StationRepository(202, "Ветово", "Vetovo"),
    StationRepository(438, "Ветрен", "Vetren"),
    StationRepository(623, "Видбол", "Vidbol"),
    StationRepository(49, "Видин Пътническа", "Vidin"),
    StationRepository(191, "Виница", "Vinica"),
    StationRepository(459, "Висока Поляна", "Visoka Poljana"),
    StationRepository(192, "Владая", "Vladaya"),
    StationRepository(165, "Владимир Павлов", "Vladimir Pavlov"),
    StationRepository(117, "Владо Тричков", "Vlado Trichkov"),
    StationRepository(229, "Власатица", "Vlasatica"),
    StationRepository(409, "Воднянци", "Vodnyanci"),
    StationRepository(184, "Волуяк", "Voluyak"),
    StationRepository(10, "Враца", "Vraca"),
    StationRepository(91, "Враца - Спирка", "Vraca Stop"),
    StationRepository(219, "Връбница", "Vrabnica"),
    StationRepository(514, "Въбел", "Vabel"),
    StationRepository(136, "Вълчи Дол", "Valchi Dol"),
    StationRepository(447, "Вълчин", "Valchin"),
    StationRepository(307, "Габарево", "Gabarevo"),
    StationRepository(295, "Габровница", "Gabrovnica"),
    StationRepository(76, "Габрово", "Gabrovo"),
    StationRepository(500, "Гавраилово", "Gavrailovo"),
    StationRepository(385, "Ганчовец", "Ganchovec"),
    StationRepository(294, "Генерал Киселово", "General Kiselovo"),
    StationRepository(411, "Генерал Ковачев", "General Kovachev"),
    StationRepository(647, "Генерал Колево", "General Kolevo"),
    StationRepository(142, "Генерал Тодоров", "General Todorov"),
    StationRepository(175, "Генерал Тошево", "General Toshevo"),
    StationRepository(402, "Глумче", "Glumche"),
    StationRepository(566, "Глухар", "Gluhar"),
    StationRepository(477, "Голяма Вода", "Goljama Voda"),
    StationRepository(390, "Голямо Дряново", "Golyamo Dryanovo"),
    StationRepository(507, "Голямо Ново", "Golyamo Novo"),
    StationRepository(406, "Голямо Село", "Golyamo Selo"),
    StationRepository(563, "Голям Поровец", "Golyam Porovec"),
    StationRepository(569, "Горица", "Gorica"),
    StationRepository(28, "Горна Баня", "Gorna Banya"),
    StationRepository(701, "Горна Баня Сп", "Stop Gorna Banya Metro"),
    StationRepository(487, "Горна Крета", "Gorna Kreta"),
    StationRepository(545, "Горна Малина", "Gorna Malina"),
    StationRepository(275, "Горна Махала", "Gorna Mahala"),
    StationRepository(5, "Горна Оряховица", "Gorna Oryahovica"),
    StationRepository(141, "Горни Дъбник", "Gorni Dabnik"),
    StationRepository(445, "Горно Ботево", "Gorno Botevo"),
    StationRepository(301, "Горско Дюлево", "Gorsko Dyulevo"),
    StationRepository(662, "Г.оряховица-пр.парк", "G.Oryahovica-pr.park"),
    StationRepository(671, "Г.оряховица Разпр.п.", "Gorna Oryahovica Razpr."),
    StationRepository(522, "Градешница", "Gradeshnica"),
    StationRepository(155, "Градище", "Gradishte"),
    StationRepository(139, "Граф Игнатиево", "Graf Ignatievo"),
    StationRepository(270, "Гривица", "Grivica"),
    StationRepository(279, "Гулийна Баня", "Gulijna Banya"),
    StationRepository(478, "Гурково", "Gurkovo"),
    StationRepository(246, "Гълъбник", "Galabnik"),
    StationRepository(676, "Гюешево", "Gjueshevo"),
    StationRepository(365, "Дагоново", "Dagonovo"),
    StationRepository(328, "Дамяница", "Damyanica"),
    StationRepository(57, "Даскалово", "Daskalovo"),
    StationRepository(80, "Две Могили", "Dve Mogili"),
    StationRepository(483, "Дебелец", "Debelec"),
    StationRepository(515, "Дебели Лак", "Debeli Lak"),
    StationRepository(383, "Девня", "Devnya"),
    StationRepository(389, "Делян", "Delyan"),
    StationRepository(582, "Джебел", "Dzhebel"),
    StationRepository(602, "Джерман", "Dzherman"),
    StationRepository(355, "Джулюница", "Dzhuljunica"),
    StationRepository(244, "Дибич", "Dibich"),
    StationRepository(502, "Дивдядово", "Divdyadovo"),
    StationRepository(359, "Димитриево", "Dimitrievo"),
    StationRepository(23, "Димитровград", "Dimitrovgrad"),
    StationRepository(637, "Димитровград Север", "Dimitrovgrad North"),
    StationRepository(617, "Димитровград Юг Сп.", "Dimitrovgrad South Stop"),
    StationRepository(197, "Димово", "Dimovo"),
    StationRepository(151, "Добрина", "Dobrina"),
    StationRepository(303, "Добринище", "Dobrinishte"),
    StationRepository(652, "Добриново", "Dobrinovo"),
    StationRepository(46, "Добрич", "Dobrich"),
    StationRepository(448, "Добрич - Север", "Dobrich North"),
    StationRepository(615, "Добродан", "Dobrodan"),
    StationRepository(613, "Дождевица", "Dozhdevica"),
    StationRepository(343, "Дойренци", "Dojrenci"),
    StationRepository(601, "Долапите", "Dolapite"),
    StationRepository(542, "Долене", "Dolene"),
    StationRepository(172, "Долна Махала", "Dolna Mahala"),
    StationRepository(505, "Долна Митрополия", "Dolna Mitropoliya"),
    StationRepository(465, "Долни Вит", "Dolni Vit"),
    StationRepository(277, "Долни Дъбник", "Dolni Dabnik"),
    StationRepository(283, "Долни Раковец", "Dolni Rakovec"),
    StationRepository(243, "Долно Езерово", "Dolno Ezerovo"),
    StationRepository(413, "Долно Камарци", "Dolno Kamarci"),
    StationRepository(585, "Долно Село", "Dolno Selo"),
    StationRepository(311, "Долно Церовене", "Dolno Cerovene"),
    StationRepository(162, "Дончево", "Donchevo"),
    StationRepository(171, "Драгичево", "Dragichevo"),
    StationRepository(212, "Драгоман", "Dragoman"),
    StationRepository(455, "Драгоман - Сп.", "Dragoman Sp"),
    StationRepository(188, "Драгомирово", "Dragomirovo"),
    StationRepository(314, "Дралфа", "Dralfa"),
    StationRepository(672, "Драсов", "Drasov"),
    StationRepository(195, "Дреновец", "Drenovec"),
    StationRepository(657, "Дропла", "Dropla"),
    StationRepository(528, "Дружба", "Druzhba"),
    StationRepository(66, "Дряново", "Drjanovo"),
    StationRepository(344, "Дряново - Сп.", "Drjanovo Stop"),
    StationRepository(429, "Дулово", "Dulovo"),
    StationRepository(296, "Дунавци", "Dunavci"),
    StationRepository(71, "Дупница", "Dupnica"),
    StationRepository(486, "Дупница - Сп.", "Dupnica Stop"), // proveri nadolu!!!
    StationRepository(316, "Дъбене", "Dabene"),
    StationRepository(419, "Дъбова Махала", "Dabova Mahala"),
    StationRepository(87, "Дъбово", "Dabovo"),
    StationRepository(643, "Дълга Лъка", "Dalga Laka"),
    StationRepository(78, "Дългопол", "Dalgopol"),
    StationRepository(331, "Дъскотна", "Daskotna"),
    StationRepository(688, "Дюлево", "Djulevo"),
    StationRepository(614, "Дяково", "Djakovo"),
    StationRepository(327, "Егълница", "Egalnica"),
    StationRepository(143, "Езерово", "Ezerovo"),
    StationRepository(621, "Езерово-спирка", "Ezerovo Spirka"),
    StationRepository(392, "Еленино", "Elenino"),
    StationRepository(32, "Елин Пелин", "Elin Pelin"),
    StationRepository(233, "Елисейна", "Elisejna"),
    StationRepository(572, "Елит", "Elit"),
    StationRepository(167, "Ерден", "Erden"),
    StationRepository(353, "Жабляно", "Zhabljano"),
    StationRepository(376, "Жеглица", "Zheglica"),
    StationRepository(648, "Железница", "Zheleznica"),
    StationRepository(247, "Желен", "Zhelen"),
    StationRepository(446, "Желъд", "Zhelad"),
    StationRepository(299, "Желю Войвода", "Zhelju Vojvoda"),
    StationRepository(544, "Желязна Врата", "Zheljazna Vrata"),
    StationRepository(315, "Живково", "Zhivkovo"),
    StationRepository(285, "Житница", "Zhitnica"),
    StationRepository(436, "Жп.школа - Лакатник", "Zhp Shkola Lakatnik"),
    StationRepository(333, "Завет", "Zavet"),
    StationRepository(527, "Завет - Сп.", "Zavet Sp"),
    StationRepository(492, "Завой", "Zavoj"),
    StationRepository(21, "Захарна Фабрика", "Zaharna Fabrika"),
    StationRepository(442, "Звезделина", "Zvezdelina"),
    StationRepository(94, "Зверино", "Zverino"),
    StationRepository(293, "Звъничево", "Zvanichevo"),
    StationRepository(435, "Здравец", "Zdravec"),
    StationRepository(79, "Земен", "Zemen"),
    StationRepository(127, "Зимница", "Zimnica"),
    StationRepository(304, "Златица", "Zlatica"),
    StationRepository(665, "Златна Нива", "Zlatna Niva"),
    StationRepository(644, "Златуша", "Zlatusha"),
    StationRepository(656, "Змейово", "Zmejovo"),
    StationRepository(372, "Иван Вазово", "Ivan Vazovo"),
    StationRepository(393, "Иванковци", "Ivankovci"),
    StationRepository(97, "Иваново", "Ivanovo"),
    StationRepository(510, "Ивански", "Ivanski"),
    StationRepository(321, "Иваняне", "Ivanjane"),
    StationRepository(597, "Иганово", "Iganovo"),
    StationRepository(103, "Илиянци", "Ilijanci"),
    StationRepository(26, "Искър", "Iskar"),
    StationRepository(696, "Искърско Шосе", "Iskarsko Shose"),
    StationRepository(190, "Исперих", "Isperih"),
    StationRepository(74, "Ихтиман", "Ihtiman"),
    StationRepository(508, "Йоглав", "Joglav"),
    StationRepository(138, "Кадиево", "Kadievo"),
    StationRepository(40, "Казанлък", "Kazanlak"),
    StationRepository(620, "Казачево", "Kazachevo"),
    StationRepository(187, "Казичене", "Kazichene"),
    StationRepository(554, "Калейца", "Kalejca"),
    StationRepository(581, "Калипетрово", "Kalipetrovo"),
    StationRepository(227, "Калитиново", "Kalitinovo"),
    StationRepository(163, "Калища", "Kalishta"),
    StationRepository(678, "Калотина-запад", "Kalotina Zapad"),
    StationRepository(305, "Калофер", "Kalofer"),
    StationRepository(129, "Калояновец", "Kalojanovec"),
    StationRepository(271, "Калояново", "Kalojanovo"),
    StationRepository(320, "Калоянци", "Kalojanci"),
    StationRepository(432, "Калугерица", "Kalugerica"),
    StationRepository(346, "Каменец", "Kamenec"),
    StationRepository(358, "Каменни Кариери", "Kamenni Karieri"),
    StationRepository(104, "Камено", "Kameno"),
    StationRepository(518, "Каменяк", "Kamenjak"),
    StationRepository(523, "Каравельово", "Karaveljovo"),
    StationRepository(183, "Карагеоргиево", "Karageorgievo"),
    StationRepository(211, "Караджалово", "Karadzhalovo"),
    StationRepository(600, "Караджата", "Karadzhata"),
    StationRepository(653, "Карбинци", "Karbinci"),
    StationRepository(222, "Кардам", "Kardam"),
    StationRepository(693, "Кариера-скакавица", "Kariera Skakavica"),
    StationRepository(38, "Карлово", "Karlovo"),
    StationRepository(282, "Карлуково", "Karlukovo"),
    StationRepository(41, "Карнобат", "Karnobat"),
    StationRepository(67, "Каспичан", "Kaspichan"),
    StationRepository(156, "Катуница", "Katunica"),
    StationRepository(225, "Кермен", "Kermen"),
    StationRepository(555, "Кесарево", "Kesarevo"),
    StationRepository(548, "Кипра", "Kipra"),
    StationRepository(567, "Китанчево", "Kitanchevo"),
    StationRepository(276, "Кликач", "Klikach"),
    StationRepository(632, "Климат.училище", "Klimat Uchilishte"),
    StationRepository(356, "Климаш", "Klimash"),
    StationRepository(350, "Клисура", "Klisura"),
    StationRepository(481, "Книжовник", "Knizhovnik"),
    StationRepository(182, "Ковачево", "Kovachevo"),
    StationRepository(405, "Козаревец", "Kozarevec"),
    StationRepository(269, "Козарско", "Kozarsko"),
    StationRepository(264, "Комарево", "Komarevo"),
    StationRepository(109, "Комунари", "Komunari"),
    StationRepository(607, "Конаре", "Konare"),
    StationRepository(616, "Кондофрей", "Kondofrej"),
    StationRepository(575, "Константиново", "Konstantinovo"),
    StationRepository(252, "Коньово", "Konjovo"),
    StationRepository(297, "Копаница", "Kopanica"),
    StationRepository(257, "Копиловци", "Kopilovci"),
    StationRepository(397, "Копривщица", "Koprivshtica"),
    StationRepository(462, "Костандово", "Kostandovo"),
    StationRepository(669, "Коста Петров", "Kosta Petrov"),
    StationRepository(39, "Костенец", "Kostenec"),
    StationRepository(98, "Костинброд", "Kostinbrod"),
    StationRepository(228, "Костинброд - Сп.", "Kostinbrod Sp"),
    StationRepository(695, "Кочево", "Kochevo"),
    StationRepository(512, "Кочериново", "Kocherinovo"),
    StationRepository(259, "Кочово", "Kochovo"),
    StationRepository(470, "Кошарите", "Kosharite"),
    StationRepository(558, "Кошов", "Koshov"),
    StationRepository(540, "Кракра", "Krakra"),
    StationRepository(475, "Кремиковци", "Kremikovci"),
    StationRepository(680, "Крепост", "Krepost"),
    StationRepository(382, "Кресна", "Kresna"),
    StationRepository(460, "Кресна - Сп.", "Kresna Sp"),
    StationRepository(437, "Крета", "Kreta"),
    StationRepository(240, "Крива Бара", "Kriva Bara"),
    StationRepository(506, "Кривня", "Krivnja"),
    StationRepository(60, "Криводол", "Krivodol"),
    StationRepository(361, "Кричим", "Krichim"),
    StationRepository(148, "Крум", "Krum"),
    StationRepository(20, "Крумово", "Krumovo"),
    StationRepository(154, "Крушето", "Krusheto"),
    StationRepository(456, "Кръстец", "Krastec"),
    StationRepository(580, "Кубратово", "Kubratovo"),
    StationRepository(414, "Кулата", "Kulata"),
    StationRepository(174, "Кумарица", "Kumarica"),
    StationRepository(189, "Кунино", "Kunino"),
    StationRepository(101, "Курило", "Kurilo"),
    StationRepository(178, "Куртово Конаре", "Kurtovo Konare"),
    StationRepository(578, "Кутугерци", "Kutugerci"),
    StationRepository(248, "Куцина", "Kucina"),
    StationRepository(132, "Кърджали", "Kardzhali"),
    StationRepository(368, "Кърнаре", "Karnare"),
    StationRepository(534, "Кършалево", "Karshalevo"),
    StationRepository(52, "Кюстендил", "Kjustendil"),
    StationRepository(404, "Лазар Пампоров", "Lazar Pamporov"),
    StationRepository(73, "Лакатник", "Lakatnik"),
    StationRepository(423, "Левище", "Levishte"),
    StationRepository(17, "Левски", "Levski"),
    StationRepository(319, "Лесичери", "Lesicheri"),
    StationRepository(428, "Леска", "Leska"),
    StationRepository(250, "Летница", "Letnica"),
    StationRepository(539, "Лешница", "Leshnica"),
    StationRepository(480, "Листец", "Listec"),
    StationRepository(249, "Ловец", "Lovec"),
    StationRepository(83, "Ловеч", "Lovech"),
    StationRepository(682, "Ловеч-север", "Lovech Sever"),
    StationRepository(300, "Ловеч - Сп.", "Lovech Sp"),
    StationRepository(651, "Ловеч - Юг", "Lovech Jug"),
    StationRepository(281, "Лозарево", "Lozarevo"),
    StationRepository(690, "Лозово", "Lozovo"),
    StationRepository(661, "Локорско", "Lokorsko"),
    StationRepository(34, "Лом", "Lom"),
    StationRepository(625, "Ломец", "Lomec"),
    StationRepository(90, "Луково", "Lukovo"),
    StationRepository(223, "Любимец", "Ljubimec"),
    StationRepository(474, "Люляково", "Ljuljakovo"),
    StationRepository(254, "Лютиброд", "Ljutibrod"),
    StationRepository(199, "Маврудово", "Mavrudovo"),
    StationRepository(232, "Мадара", "Madara"),
    StationRepository(525, "Мазарачево", "Mazarachevo"),
    StationRepository(450, "Макоцево", "Makocevo"),
    StationRepository(524, "Макоцево - Сп.", "Makocevo Sp"),
    StationRepository(660, "Макреш", "Makresh"),
    StationRepository(574, "Малево", "Malevo"),
    StationRepository(608, "Мало Село", "Malo Selo"),
    StationRepository(241, "Маноле", "Manole"),
    StationRepository(309, "Манолово", "Manolovo"),
    StationRepository(520, "Марек", "Marek"),
    StationRepository(517, "Марикостино", "Marikostino"),
    StationRepository(425, "Марино Поле", "Marino Pole"),
    StationRepository(642, "Марко Николов", "Marko Nikolov"),
    StationRepository(593, "Маслиново", "Maslinovo"),
    StationRepository(119, "Медковец", "Medkovec"),
    StationRepository(401, "Медовина", "Medovina"),
    StationRepository(457, "Межден", "Mezhden"),
    StationRepository(8, "Мездра", "Mezdra"),
    StationRepository(348, "Мездра Юг", "Mezdra Jug"),
    StationRepository(504, "Меричлери", "Merichleri"),
    StationRepository(273, "Меричлери-сп.", "Merichleri Sp"),
    StationRepository(22, "Метал-сп.", "Metal Stop"),
    StationRepository(531, "Милковица", "Milkovica"),
    StationRepository(494, "Мирково", "Mirkovo"),
    StationRepository(622, "Мирково - Сп.", "Mirkovo St"),
    StationRepository(144, "Михайлово", "Mihajlovo"),
    StationRepository(251, "Михалци-стамболово", "Mihalci Stambolovo"),
    StationRepository(619, "Мламолово", "Mlamolovo"),
    StationRepository(326, "Мокрище", "Mokrishte"),
    StationRepository(201, "Момина Клисура", "Momina Klisura"),
    StationRepository(479, "Момина Скала", "Momina Skala"),
    StationRepository(230, "Момин Брод", "Momin Brod"),
    StationRepository(274, "Момин Проход", "Momin Prohod"),
    StationRepository(135, "Момчилград", "Momchilgrad"),
    StationRepository(27, "Монтана", "Montana"),
    StationRepository(131, "Морава", "Morava"),
    StationRepository(468, "Моравица", "Moravica"),
    StationRepository(681, "Моруница", "Morunica"),
    StationRepository(579, "Моряк", "Morjak"),
    StationRepository(590, "Мост", "Most"),
    StationRepository(556, "Мулетарово", "Muletarovo"),
    StationRepository(364, "Мурсалево", "Mursalevo"),
    StationRepository(683, "Мусачево", "Musachevo"),
    StationRepository(634, "Мъдрец", "Madrec"),
    StationRepository(220, "Мърчево", "Marchevo"),
    StationRepository(557, "Мътница", "Matnica"),
    StationRepository(260, "Надарево", "Nadarevo"),
    StationRepository(180, "Надежда - Сп.", "Nadezhda"),
    StationRepository(570, "Невестино", "Nevestino"),
    StationRepository(335, "Невша", "Nevsha"),
    StationRepository(641, "Негован", "Negovan"),
    StationRepository(561, "Негушево", "Negushevo"),
    StationRepository(498, "Немирово", "Nemirovo"),
    StationRepository(268, "Николаево", "Nikolaevo"),
    StationRepository(59, "Нова Загора", "Nova Zagora"),
    StationRepository(209, "Нова Надежда", "Nova Nadezhda"),
    StationRepository(123, "Нова Шипка", "Nova Shipka"),
    StationRepository(560, "Обединена", "Obedinena"),
    StationRepository(239, "Обеля", "Obelja"),
    StationRepository(258, "Оборище", "Oborishte"),
    StationRepository(509, "Образцов Чифлик", "Obrazcov Chiflik"),
    StationRepository(13, "Овчеполци", "Ovchepolci"),
    StationRepository(287, "Огняново", "Ognjanovo"),
    StationRepository(451, "Одърне", "Odarne"),
    StationRepository(485, "Оплетня", "Opletnja"),
    StationRepository(237, "Опълченец", "Opalchenec"),
    StationRepository(374, "Ореш", "Oresh"),
    StationRepository(618, "Орешак", "Oreshak"),
    StationRepository(116, "Орешец", "Oreshec"),
    StationRepository(122, "Оризово", "Orizovo"),
    StationRepository(100, "Орлин", "Orlin"),
    StationRepository(464, "Оселна", "Oselna"),
    StationRepository(370, "Осетеново", "Osetenovo"),
    StationRepository(603, "Ослен", "Oslen"),
    StationRepository(650, "Острец", "Ostrec"),
    StationRepository(193, "Отдих", "Otdih"),
    StationRepository(290, "Охрид", "Ohrid"),
    StationRepository(342, "Павел Баня", "Pavel Banja"),
    StationRepository(42, "Павликени", "Pavlikeni"),
    StationRepository(16, "Пазарджик", "Pazardzhik"),
    StationRepository(490, "Пали Лула", "Pali Lula"),
    StationRepository(684, "Панагюрище", "Panagjurishte"),
    StationRepository(310, "Партизани", "Partizani"),
    StationRepository(630, "Пейо Яворов", "Pejo Javorov"),
    StationRepository(7, "Перник", "Pernik"),
    StationRepository(31, "Перник Разпределит.", "Pernik Razpredelit"),
    StationRepository(329, "Перперек", "Perperek"),
    StationRepository(439, "Песнопой", "Pesnopoj"),
    StationRepository(177, "Петко Каравелово", "Petko Karavelovo"),
    StationRepository(145, "Петрич", "Petrich"),
    StationRepository(469, "Петърч", "Petarch"),
    StationRepository(106, "Пещера", "Peshtera"),
    StationRepository(205, "Пирдоп", "Pirdop"),
    StationRepository(150, "Плачковци", "Plachkovci"),
    StationRepository(6, "Плевен", "Pleven"),
    StationRepository(213, "Плевен Запад", "Pleven Zapad"),
    StationRepository(649, "Плиска", "Pliska"),
    StationRepository(3, "Пловдив", "Plovdiv"),
    StationRepository(691, "Плоска Могила", "Ploska Mogila"),
    StationRepository(238, "Побит Камък", "Pobit Kamak"),
    StationRepository(47, "Повеляново", "Poveljanovo"),
    StationRepository(559, "Подвис", "Podvis"),
    StationRepository(391, "Подгорица", "Podgorica"),
    StationRepository(224, "Подем", "Podem"),
    StationRepository(286, "Подкова", "Podkova"),
    StationRepository(35, "Подуяне", "Podujane Passenger"),
    StationRepository(516, "Подуяне Разпр.ср.р.", "Podujane Razprsrr"),
    StationRepository(394, "Поликраище", "Polikraishte"),
    StationRepository(605, "Полски Сеновец", "Polski Senovec"),
    StationRepository(70, "Полски Тръмбеш", "Polski Trambesh"),
    StationRepository(204, "Полско Косово", "Polsko Kosovo"),
    StationRepository(120, "Поповица", "Popovica"),
    StationRepository(75, "Попово", "Popovo"),
    StationRepository(198, "Пордим", "Pordim"),
    StationRepository(433, "Правда", "Pravda"),
    StationRepository(666, "Преколница", "Prekolnica"),
    StationRepository(550, "Преславец", "Preslavec"),
    StationRepository(357, "Прибой", "Priboj"),
    StationRepository(584, "Прилеп", "Prilep"),
    StationRepository(63, "Провадия", "Provadija"),
    StationRepository(403, "Пролет", "Prolet"),
    StationRepository(181, "Прослав", "Proslav"),
    StationRepository(308, "Просторно", "Prostorno"),
    StationRepository(216, "Птичар", "Ptichar"),
    StationRepository(45, "Първомай", "Parvomaj"),
    StationRepository(639, "Равна", "Ravna"),
    StationRepository(482, "Равнец", "Ravnec"),
    StationRepository(577, "Равно Поле", "Ravno Pole"),
    StationRepository(214, "Раданово", "Radanovo"),
    StationRepository(583, "Радевци", "Radevci"),
    StationRepository(388, "Радко Димитриево", "Radko Dimitrievo"),
    StationRepository(466, "Радовене", "Radovene"),
    StationRepository(44, "Радомир", "Radomir"),
    StationRepository(496, "Радуй", "Raduj"),
    StationRepository(454, "Радунци", "Radunci"),
    StationRepository(164, "Раждавица", "Razhdavica"),
    StationRepository(159, "Разград", "Razgrad"),
    StationRepository(194, "Разделна", "Razdelna"),
    StationRepository(262, "Разлог", "Razlog"),
    StationRepository(596, "Разменна", "Razmenna"),
    StationRepository(674, "Разменна - Сп.", "Razmenna Sp"),
    StationRepository(85, "Ракево", "Rakevo"),
    StationRepository(635, "Раковски", "Rakovski"),
    StationRepository(105, "Реброво", "Rebrovo"),
    StationRepository(323, "Ребърково", "Rebarkovo"),
    StationRepository(595, "Реселец - Сп.", "Reselec Sp"),
    StationRepository(337, "Ресен", "Resen"),
    StationRepository(408, "Рогозче", "Rogozche"),
    StationRepository(289, "Розино", "Rozino"),
    StationRepository(65, "Роман", "Roman"),
    StationRepository(86, "Ромча", "Romcha"),
    StationRepository(519, "Руйно", "Rujno"),
    StationRepository(458, "Рупите", "Rupite"),
    StationRepository(664, "Рупци - Север", "Rupci Sever"),
    StationRepository(587, "Русаля - Дичин", "Rusalja Dichin"),
    StationRepository(30, "Русе", "Ruse"),
    StationRepository(128, "Русе Разпределителна", "Ruse Razpredelitelna"),
    StationRepository(146, "Русе Товарна-сп.", "Ruse Tovarna Sp"),
    StationRepository(312, "Руска Бяла", "Ruska Bjala"),
    StationRepository(69, "Садово", "Sadovo"),
    StationRepository(386, "Самоводене", "Samovodene"),
    StationRepository(92, "Самуил", "Samuil"),
    StationRepository(261, "Самуилово", "Samuilovo"),
    StationRepository(206, "Сандански", "Sandanski"),
    StationRepository(655, "Саранци", "Saranci"),
    StationRepository(424, "Сахране", "Sahrane"),
    StationRepository(332, "Сборище", "Sborishte"),
    StationRepository(533, "Свежен", "Svezhen"),
    StationRepository(511, "Света Петка", "Sveta Petka"),
    StationRepository(692, "Свети Георги", "Sveti Georgi"),
    StationRepository(562, "Светлен", "Svetlen"),
    StationRepository(521, "Светлина - Сп.", "Svetlina Sp"),
    StationRepository(624, "Световрачане", "Svetovrachane"),
    StationRepository(153, "Свиленград", "Svilengrad"),
    StationRepository(64, "Свищов", "Svishtov"),
    StationRepository(369, "Свобода", "Svoboda"),
    StationRepository(18, "Своге", "Svoge"),
    StationRepository(551, "Селиминово", "Seliminovo"),
    StationRepository(226, "Сеново", "Senovo"),
    StationRepository(24, "Септември", "Septemvri"),
    StationRepository(354, "Сестримо", "Sestrimo"),
    StationRepository(210, "Силистра", "Silistra"),
    StationRepository(200, "Симеоновград", "Simeonovgrad"),
    StationRepository(317, "Симитли", "Simitli"),
    StationRepository(659, "Синаговци-гурково", "Sinagovci Gurkovo"),
    StationRepository(88, "Синдел", "Sindel"),
    StationRepository(284, "Синитово", "Sinitovo"),
    StationRepository(336, "Синьо Бърдо", "Sinjo Bardo"),
    StationRepository(552, "Скакавица", "Skakavica"),
    StationRepository(169, "Скобелево", "Skobelevo"),
    StationRepository(604, "Скомля (кантон-43)", "Skomlja Kanton 43"),
    StationRepository(95, "Скутаре", "Skutare"),
    StationRepository(203, "Славяново", "Slavjanovo"),
    StationRepository(673, "Слана Бара", "Slana Bara"),
    StationRepository(43, "Сливен", "Sliven"),
    StationRepository(234, "Сливница", "Slivnica"),
    StationRepository(147, "Сливница - Сп.", "Slivnica Sp"),
    StationRepository(687, "Смилец", "Smilec"),
    StationRepository(157, "Смирненски", "Smirnenski"),
    StationRepository(573, "Смолево", "Smolevo"),
    StationRepository(334, "Смядово", "Smjadovo"),
    StationRepository(612, "Соволяно", "Sovoljano"),
    StationRepository(292, "Соколово", "Sokolovo"),
    StationRepository(422, "Солна Мина", "Solna Mina"),
    StationRepository(418, "Сомовит", "Somovit"),
    StationRepository(546, "Сопот", "Sopot"),
    StationRepository(2, "София", "Sofia"),
    StationRepository(54, "София Север", "Sofia Sever"),
    StationRepository(529, "Спасово", "Spasovo"),
    StationRepository(497, "Срацимир", "Sracimir"),
    StationRepository(568, "Средна Арда", "Sredna Arda"),
    StationRepository(484, "Стайновци", "Stajnovci"),
    StationRepository(340, "Сталево", "Stalevo"),
    StationRepository(108, "Сталийска Махала", "Stalijska Mahala"),
    StationRepository(14, "Стамболийски", "Stambolijski"),
    StationRepository(349, "Стамболово", "Stambolovo"),
    StationRepository(638, "Стамо Костов", "Stamo Kostov"),
    StationRepository(11, "Стара Загора", "Stara Zagora"),
    StationRepository(675, "Стара Кресна", "Stara Kresna"),
    StationRepository(543, "Стойчевци", "Stojchevci"),
    StationRepository(431, "Столник", "Stolnik"),
    StationRepository(699, "Стоян Митов", "Stojan Mitov"),
    StationRepository(81, "Стражица", "Strazhica"),
    StationRepository(121, "Стралджа", "Straldzha"),
    StationRepository(179, "Страшимирово", "Strashimirovo"),
    StationRepository(685, "Стрелча", "Strelcha"),
    StationRepository(646, "Строител", "Stroitel"),
    StationRepository(339, "Струмяни", "Strumjani"),
    StationRepository(373, "Струпец", "Strupec"),
    StationRepository(130, "Струя", "Struja"),
    StationRepository(499, "Стряма", "Strjama"),
    StationRepository(473, "Стърмен", "Starmen"),
    StationRepository(170, "Суворово", "Suvorovo"),
    StationRepository(306, "Съботковци", "Sabotkovci"),
    StationRepository(463, "Съединение", "Saedinenie"),
    StationRepository(670, "Табачка", "Tabachka"),
    StationRepository(476, "Таню Войвода", "Tanju Vojvoda"),
    StationRepository(158, "Твърдица", "Tvardica"),
    StationRepository(118, "Телиш", "Telish"),
    StationRepository(96, "Тодор Каблешков", "Todor Kableshkov"),
    StationRepository(530, "Тодорово", "Todorovo"),
    StationRepository(125, "Томпсън", "Tompsan"),
    StationRepository(341, "Тополите", "Topolite"),
    StationRepository(267, "Тополица", "Topolica"),
    StationRepository(152, "Тополов Дол", "Topolov Dol"),
    StationRepository(288, "Трайково", "Trajkovo"),
    StationRepository(110, "Тракия", "Trakija"),
    StationRepository(352, "Тракия (шумен)", "Trakija Shumen"),
    StationRepository(541, "Трапезица", "Trapezica"),
    StationRepository(266, "Троян", "Trojan"),
    StationRepository(207, "Труд", "Trud"),
    StationRepository(149, "Тръстиково", "Trastikovo"),
    StationRepository(55, "Трявна", "Trjavna"),
    StationRepository(72, "Тулово", "Tulovo"),
    StationRepository(236, "Тъжа", "Tazha"),
    StationRepository(36, "Търговище", "Targovishte"),
    StationRepository(93, "Търнак", "Tarnak"),
    StationRepository(351, "Търничени", "Tarnicheni"),
    StationRepository(547, "Узунджово", "Uzundzhovo"),
    StationRepository(366, "Умаревци", "Umarevci"),
    StationRepository(488, "Усойка", "Usojka"),
    StationRepository(82, "Филипово", "Filipovo"),
    StationRepository(208, "Хаджиево", "Hadzhievo"),
    StationRepository(161, "Хан Аспарух", "Han Asparuh"),
    StationRepository(280, "Хан Крум", "Han Krum"),
    StationRepository(196, "Харманли", "Harmanli"),
    StationRepository(698, "Харманли Център", "Harmanli Central"),
    StationRepository(318, "Хасково", "Haskovo"),
    StationRepository(576, "Хераково", "Herakovo"),
    StationRepository(114, "Хисар", "Hisar"),
    StationRepository(378, "Хитрино", "Hitrino"),
    StationRepository(679, "Хлевене", "Hlevene"),
    StationRepository(420, "Храбърско", "Hrabarsko"),
    StationRepository(338, "Християново", "Hristijanovo"),
    StationRepository(427, "Христо Даново", "Hristo Danovo"),
    StationRepository(668, "Хумата", "Humata"),
    StationRepository(532, "Хърсово", "Harsovo"),
    StationRepository(686, "Цар Асен", "Car Asen"),
    StationRepository(677, "Царацово", "Caracovo"),
    StationRepository(48, "Царева Ливада", "Careva Livada"),
    StationRepository(565, "Царева Поляна", "Careva Poljana"),
    StationRepository(218, "Царевци", "Carevci"),
    StationRepository(291, "Цветино", "Cvetino"),
    StationRepository(626, "Цепина", "Cepina"),
    StationRepository(265, "Церковски", "Cerkovski"),
    StationRepository(410, "Церовица", "Cerovica"),
    StationRepository(68, "Церово", "Cerovo"),
    StationRepository(628, "Чавдарци", "Chavdarci"),
    StationRepository(430, "Чеканчево", "Chekanchevo"),
    StationRepository(434, "Челопеч", "Chelopech"),
    StationRepository(631, "Червена", "Chervena"),
    StationRepository(415, "Червена Вода", "Chervena Voda"),
    StationRepository(29, "Червен Бряг", "Cherven Brjag"),
    StationRepository(381, "Черганово", "Cherganovo"),
    StationRepository(663, "Черепиш", "Cherepish"),
    StationRepository(387, "Черквица", "Cherkvica"),
    StationRepository(168, "Черна Гора", "Cherna Gora"),
    StationRepository(501, "Черна Места", "Cherna Mesta"),
    StationRepository(272, "Чернево", "Chernevo"),
    StationRepository(594, "Черник", "Chernik"),
    StationRepository(441, "Черниче", "Cherniche"),
    StationRepository(217, "Черничево", "Chernichevo"),
    StationRepository(629, "Черногорово", "Chernogorovo"),
    StationRepository(347, "Черноград", "Chernograd"),
    StationRepository(263, "Чернозем", "Chernozem"),
    StationRepository(526, "Честово-сп.", "Chestovo Sp"),
    StationRepository(140, "Чешнегирово", "Cheshnegirovo"),
    StationRepository(537, "Чинтулово", "Chintulovo"),
    StationRepository(84, "Чирпан", "Chirpan"),
    StationRepository(493, "Чифлик", "Chiflik"),
    StationRepository(610, "Чуковец", "Chukovec"),
    StationRepository(592, "Чумерна", "Chumerna"),
    StationRepository(215, "Шивачево", "Shivachevo"),
    StationRepository(313, "Широко Поле", "Shiroko Pole"),
    StationRepository(160, "Шишковци", "Shishkovci"),
    StationRepository(15, "Шумен", "Shumen"),
    StationRepository(221, "Юнак", "Junak"),
    StationRepository(360, "Юруково", "Jurukovo"),
    StationRepository(99, "Ябълково", "Jabalkovo"),
    StationRepository(654, "Яворовец", "Javorovec"),
    StationRepository(645, "Ягода", "Jagoda"),
    StationRepository(375, "Ягодово", "Jagodovo"),
    StationRepository(242, "Якоруда", "Jakoruda"),
    StationRepository(700, "Якорудска Минерала Баня", "Jakorudska Minerala Banja"),
    StationRepository(25, "Ямбол", "Jambol"),
    StationRepository(586, "Яна", "Jana"),
    StationRepository(325, "Янтра", "Jantra"),
    StationRepository(363, "Ясен", "Jasen"),
    StationRepository(633, "Ясеновец", "Jasenovec"),
    StationRepository(564, "Ястребово", "Jastrebovo"),
    StationRepository(598, "Яхиново", "Jahinovo"),
)